### ISSUE TITLE
Upload pdf/image to a short link

### ISSUE THREAD

**Issue by leonardloo** [opengovsg/GoGovSG#13] opened 2019-05-15 07:37 UTC
**This is an enhancement request**
Instead of just shortening long links can we allow user to upload pdf/image which will generate a short link? Users might wish to share a poster but not as intuitive for them to host the image themselves and then shorten it.

An example of how an existing user is doing this: https://www.iras.gov.sg/irashome/uploadedfiles/irashome/quick_links/r1.pdf

_Longer term considerations_
If we move go.gov.sg to government intranet network, we can start shortening email attachments too. We could look at building an Outlook plugin to auto shorten large attachments into links like those in Gmail.

Note that we should make it clear this pdf/image that the user is uploading should be not be a sensitive content (unclassified in government terms).  If we want to support classified pdf/image, we can plug the private key into the link, encrypt the content, then send it to our server (although in this case we won't be shortening that link anymore).

**Comment by liangyuanruo** [comment] 2020-04-29 14:19
Duplicate of #35

**Closed by liangyuanruo** 2020-04-29 14:19 UTC
