### ISSUE TITLE
Link directory for admins to lookup ownership of links

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#500] opened 2020-08-28 05:55 UTC
**Is your feature request related to a problem? Please describe.**
Users tend to contact the team to find out ownership of links. Creating an internal directory is a simple feature that would help reduce the ops workload on the team.

**Describe the solution you'd like**
An internal directory page for link admins to find out who owns which links.

**Comment by lisatjide** [comment] 2020-08-28 06:54
@liangyuanruo this is a duplicate of #420

**Comment by lisatjide** [comment] 2020-09-01 05:05
closing this issue since there's a duplicate

**Closed by lisatjide** 2020-09-01 05:05 UTC
Labels: design, enhancement, pending design
