### ISSUE TITLE
Lion's crest not appearing in banner on IE

### ISSUE THREAD

**Issue by yong-jie** [opengovsg/GoGovSG#971] opened 2020-11-25 07:52 UTC
**Screenshots**
![image](https://user-images.githubusercontent.com/16982839/100197960-1743f080-2f36-11eb-9215-f2bda67b25e7.png)

**Comment by LoneRifle** [comment] 2020-11-25 07:53
Duplicate of #256

**Closed by LoneRifle** 2020-11-25 07:53 UTC
Labels: P2, bug, good first issue
