### ISSUE TITLE
Transition page countdown to be reduced to 6s

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#398] opened 2020-08-12 07:02 UTC
**Is your feature request related to a problem? Please describe.**
Current transition page have a countdown timer of 8s. Upon investigation, the drop off on transition page remains at about 14.3%. By decreasing the transition countdown period, we want to bring down the drop off even further to less than 10% 

**Describe the solution you'd like**
6s transition countdown instead of 8s.

**Comment by LoneRifle** [comment] 2020-08-12 07:05
Duplicate of #395

**Closed by LoneRifle** 2020-08-12 07:05 UTC
Labels: P1, enhancement
