### ISSUE TITLE
DDoS on local environment 

### ISSUE THREAD

**Issue by Oxiang** [opengovsg/GoGovSG#660] opened 2020-09-29 08:59 UTC
**Describe the bug**

Self-DDoS in local environment when there no data in the database.

This happens when the home page tries to call the endpoint at /api/stats. 
When calling the endpoint, StatsRepository will try to fetch clickCount from Url.count('clicks'). 
When the database is empty/does not have 'click' data, Url.count('clicks') will return NaN.  
The endpoint will subsequently return clickCount with NULL.
Back to the client, loadStats() will reject the NULL value and will call the endpoint again, thus creating DDoS on local env.

**To Reproduce**
1. Wipe all data from volumes in docker (clearing database)
docker rm -f $(docker ps -a -q)
docker volume rm $(docker volume ls -q)

2. Run the local env
npm run dev

3. Load the homepage on browser

**Expected behavior**
Witness the DDoS hitting /api/stats 

**Screenshots**
On chrome
<img width="870" alt="Screenshot 2020-09-29 at 4 55 14 PM" src="https://user-images.githubusercontent.com/29625514/94535882-ab664400-0274-11eb-83ea-51b90aaa38fa.png">

On console
![Screenshot 2020-09-29 at 4 55 33 PM](https://user-images.githubusercontent.com/29625514/94535968-c3d65e80-0274-11eb-8a89-82fb559fa4a1.png)

**Additional context**
Sequeliz .count() function returns NaN when database is empty.

**Comment by liangyuanruo** [comment] 2020-09-29 09:07
Duplicate of #659

**Closed by liangyuanruo** 2020-09-29 09:07 UTC
