### ISSUE TITLE
Long links cut off the screen on admin panel

### ISSUE THREAD

**Issue by leonardloo** [opengovsg/GoGovSG#247] opened 2020-07-02 09:29 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/4787315/86341558-0c3bab80-bc89-11ea-8ffb-f540ef8fee30.png)
![image](https://user-images.githubusercontent.com/4787315/86341758-4e64ed00-bc89-11ea-998f-16ae4c7ed1fd.png)

For long and short links, screen is cut off at Copy and can't scroll right.

**To Reproduce**
1. Create a very long short and long link
2. Right side is cut off for that row

**Expected behavior**
Suggest to restrict width and cut off with ellipses.

**Desktop (please complete the following information):**
 - Chrome
 - Mac OS
 - Large desktop screen

**Comment by LoneRifle** [comment] 2020-08-07 02:52
Suggestion - deliberately truncate URLs (long or short) with ellipsis suffix to preserve UI layout, but reveal tooltip showing full URL on mouseover. This is common, and seen at least in YouTube video entries with long titles

**Comment by LoneRifle** [comment] 2020-08-14 04:44
Duplicate of #411

**Closed by LoneRifle** 2020-08-14 04:44 UTC
Labels: P3, good first issue
